config/routes.rb
Rails.application.routes.draw do
  get 'tags', to: "tags#index"
  devise_for :users
  resources :questions do
    member do
      get "like", to: "questions#upvote"
      get "dislike", to: "questions#downvote"
    end
    resources :answers do
      member do
        get "like", to: "answers#upvote"
        get "dislike", to: "answers#downvote"
      end
    end
  end
  root 'questions#index'
  match 'tagged' => 'questions#tagged', :via => [:get], :as => 'tagged'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  acts_as_votable
end

app/models/question.rb
class Question < ActiveRecord::Base
    acts_as_votable
    acts_as_taggable
    belongs_to :user
    has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :authenticate_user!

    def create
        @question = Question.find(params[:question_id])
        @answer = Answer.create(params[:answer].permit(:content))
        @answer.user_id = current_user.id
        @answer.question_id = @question.id

        if @answer.save
            redirect_to question_path(@question)
        else
            render 'new'
        end
    end

    def upvote
        @answer = Answer.find(params[:id])
        @answer.upvote_by current_user
        redirect_to :back
    end


    def downvote
      @answer = Answer.find(params[:id])
      @answer.downvote_by current_user
      redirect_to :back
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	  devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :find_question, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
    before_action :authenticate_user!, except: [:index, :show, :tagged]
    before_action :search_init

    def index
        parse_params()
        @search = Question.search(params[:q])
        @questions = @search.result.order("created_at DESC").uniq
        #@questions = Question.all.order("created_at DESC")
        @users     = User.all
    end

    def show
      # @answers = Answer.where(question_id: @question)
      parse_params()
      @search = Question.search(params[:q])

      @answers = Answer.where(question_id: @question).order(:cached_weighted_score).reverse
    end

    def new
        @questions = @search.result.order("created_at DESC").uniq
        @question = current_user.questions.build
    end

    def create
        @question = current_user.questions.build(question_params)
        if @question.save
            redirect_to @question
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @question.update(question_params)
            redirect_to @question
        else
            render 'edit'
        end
    end

    def destroy
        @question.destroy
        redirect_to root_path
    end

    def upvote
        @question.upvote_by current_user
        redirect_to :back
    end

    def downvote
        @question.downvote_by current_user
        redirect_to :back
    end

    def tagged
      @users = User.all
      if params[:tag].present?
        @questions = Question.tagged_with(params[:tag]).order("created_at DESC")
      else
        @questions = Question.all.order("created_at DESC")
      end
    end

    private

    def find_question
        @question = Question.find(params[:id])
    end

    def question_params
        params.require(:question).permit(:title, :description, :tag_list)
    end

    def search_init
      @search = Question.search(params[:q])
    end

    def parse_params
        if params[:q] != nil
            params[:q][:combinator] = 'or'
            params[:q][:groupings] = []
            custom_words = params[:q].delete('description_or_title_or_tags_name_cont_any')
            custom_words.split(' ').each_with_index do |word, index|
                params[:q][:groupings][index] = {description_or_title_or_tags_name_cont_any: word}
            end
        end
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :search_init

  def index
    @tags = tag_list()
  end

  def tag_list
    @tags = ActsAsTaggableOn::Tag.all()
    @list = {}

    @tags.each do |tag|
      @list[tag] = tag.taggings_count
    end

    return @list.sort {|a1 ,a2| a2[1]<=>a1[1]}
  end

  private

  def search_init
    @search = Question.search(params[:q])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/answers/_form.html.haml
= simple_form_for([@question, @question.answers.build]) do |f|
    = f.input :content, as: :ckeditor, input_html: { ckeditor: { toolbar: 'mini'}}, label: false, required: true
    = f.button :submit, 'Responder', class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title BIBLOUS
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  %link{:rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"}/
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to image_tag('biblous.png'), root_path, id: "logo"
      .search
        - if @search != nil
          = search_form_for @search do |f|
            .field
              = f.search_field :description_or_title_or_tags_name_cont_any, placeholder: "Perguntas, tags"
              %i.fa.fa-search
      %nav
        - if user_signed_in?
          = link_to "Nova Pergunta", new_question_path
          = link_to "Tags", tags_path
          = link_to "Sair", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/questions/_form.html.haml
= simple_form_for @question do |f|
    = f.input :title, required: true, placeholder: 'Sua pergunta'
    %br
    = f.input :description, as: :ckeditor, input_html: { ckeditor: { toolbar: 'mini'}}, label: false, required: true
    %br
    = f.input :tag_list, label: 'Lista de TAGs (separada por vírgulas).', placeholder: 'Ex: Filipenses, Paulo'

    = f.button :submit, class: 'button'

app/views/questions/edit.html.haml
.wrapper
  %h1 Edit question

  = render 'form'

app/views/questions/index.html.haml
.wrapper
  - if !user_signed_in?
    .welcome_alert
      %span.closebtn{:onclick => "this.parentElement.style.display='none';"}
        &times
      Bem-vindo ao BIBLIOUS.

  %h1.title Perguntas
  - @questions.each do |question|
    .question
      .question_title
        = link_to question.title, question
      .question_author
        por #{@users.find(question.user_id).name}, #{time_ago_in_words(question.created_at)} atrás.
      .description
        = link_to strip_tags(question.description).truncate_words(20), question
        %br
      .footer_q
        - question.tag_list.each do |tag|
          = link_to tagged_url(:tag=> tag) do
            .tag_btn #{tag.capitalize}
        .number
          .tag_btn
            #{question.answers.count} Respostas

app/views/questions/new.html.haml
.wrapper
  %h1 Nova Pergunta

  = render 'form'

app/views/questions/show.html.haml
.wrapper
  .question_ans
    .title
      = @question.title
      .tools
        - if user_signed_in? && @question.user_id == current_user.id
          = link_to edit_question_path(@question) do
            %i.edit.fa.fa-pencil-square-o
          = link_to question_path(@question), method: :delete, data: { confirm: "Are you sure?" } do
            %i.trash.fa.fa-trash

    .description
      = @question.description.html_safe
    .footer_ans
      .author
        %p
          por
          %span #{@question.user.name}
      .likes
        = @question.get_upvotes.size
        = link_to like_question_path(@question), method: :get do
          %i.up.fa.fa-thumbs-o-up
        = @question.get_downvotes.size
        = link_to dislike_question_path(@question), method: :get do
          %i.down.fa.fa-thumbs-o-down

  %h2.answer_count= pluralize(@question.answers.count, "Respostas")
  - @answers.each do |answer|
    .answer
      .content= answer.content.html_safe
      .footer_answ
        .author
          %p
            por
            %span #{answer.user.name}
        .likes
          = answer.get_upvotes.size
          = link_to like_question_answer_path(@question, answer), method: :get do
            %i.up.fa.fa-thumbs-o-up
          = answer.get_downvotes.size
          = link_to dislike_question_answer_path(@question, answer), method: :get do
            %i.down.fa.fa-thumbs-o-down

  %br
  = render 'answers/form'

app/views/questions/tagged.html.haml
.wrapper
  %h1.title Tag: #{params[:tag]}
  - @questions.each do |question|
    .question
      .question_title
        = link_to question.title, question
      .question_author
        por #{@users.find(question.user_id).name}, #{time_ago_in_words(question.created_at)} atrás.
      .description
        = link_to strip_tags(question.description).truncate_words(20), question
        %br
      .footer_q
        - question.tag_list.each do |tag|
          = link_to tagged_url(:tag=> tag) do
            .tag_btn #{tag.capitalize}
        .number
          .tag_btn
            #{question.answers.count} Respostas

app/views/tags/index.html.haml
.wrapper
  %h1.title Tags
  .tags
    - @tags.each do |tag, count|
      = link_to tagged_url(:tag=> tag.name) do
        .tag_btn #{tag.to_s.capitalize} #{count}